version: 2

sources:
  - name: northwind_erp
    description: This is the northwind erp postgres database replica
    tables:
      - name: orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time

      - name: order_details
      - name: products
      - name: shippers
      - name: employees
      - name: customers
      - name: suppliers